### ISSUE TITLE
refactor(geometry): replace Cython pygeom without performance regression

### ISSUE THREAD

**Issue by ruddyscent** [ruddyscent/gmes#113]
## Decision

Replace the remaining `gmes.pygeom` Cython extension with a pure-Python geometry model and a bounded NumPy lowering path. Preserve the public geometry and material base APIs, numerical mapping semantics, serialization behavior, and the initialization-performance gains established by #102 / PR #111.

This must not be a line-for-line translation of `src/pygeom.pyx`. Pointwise Python tree traversal over every Yee cell would regress initialization. Make a backend-neutral, region-ID-based geometry map the bulk contract, and implement built-in shapes with bounding-slice vectorization and bounded temporary storage.

The current C++/SWIG field-update backend remains the reference and execution backend for this issue. PyTorch and native-kernel replacement are out of scope.

## Motivation

After #100 moved the high-level material layer to Python, `src/pygeom.pyx` is the only remaining Cython source. It currently owns both public model classes (`Material`, `Compound`, `GeomBox`, `GeomBoxTree`, and the geometric primitives) and the bulk Yee-grid lookup used by FDTD and TFSF initialization.

Removing this extension should:

- eliminate the Cython build dependency and one compiled extension without slowing the current solver;
- separate geometry semantics from the current C++/SWIG updater API;
- avoid returning one Python material object per mapped cell;
- provide flat, validated data that a future Torch CPU/CUDA backend can lower into tensors once, without making this issue depend on PyTorch;
- make geometry classes, subclassing, testing, packaging, and maintenance ordinary Python concerns.

## Current reference

Use `f3f062761fdbec8906b691806cb8e2c29bcb2bdd` as the initial Cython reference commit. PR #111 reported the following macOS arm64 initialization medians after adding bounded Cython batch lookup:

- heterogeneous case: 2.6779 s to 1.6103 s;
- 3-D case: 10.4336 s to 8.0427 s.

The replacement must compare against the current post-#111 implementation, not the older pointwise baseline.

## Target lowering contract

Introduce a backend-neutral logical `GeometryMap` (the exact public/private name may be chosen during implementation) containing, per Yee component or bounded tile:

- C-contiguous material region IDs;
- C-contiguous underlying-region IDs for `Compound` resolution;
- the mapped shape, component, and linear/tile bounds;
- a stable table mapping region IDs to material descriptors or material objects needed by the current backend;
- enough metadata to validate coverage, ordering, bounds, dtype, and shape.

The logical map may be produced or consumed as bounded tiles so large 3-D problems do not require full coordinate meshes or unbounded temporaries. Neither the contract nor the geometry classes should expose C++-, SWIG-, Rust-, or Torch-specific updater objects.

## Bulk mapping strategy

For built-in geometry:

1.  Precompute the MPI-local coordinate axes for each Yee component.
2.  Convert each object's bounding box to clipped grid slices.
3.  Evaluate `DefaultMedium`, `Cone`, `Cylinder`, `Block`, `Ellipsoid`, `Sphere`, and `Shell` predicates with NumPy broadcasting inside only those slices and bounded tiles.
4.  Apply objects in existing list order so the last matching object wins.
5.  Before a `Compound` region overwrites a cell, record the previously mapped region as its underlying region, preserving consecutive and overlapping compound semantics. Clear that underlying ID when a later non-`Compound` region wins.
6.  Let the new internal lowering path consume integer IDs rather than per-cell Python object lists.

Do not allocate full `meshgrid` coordinate arrays. Keep point lookup for the public `object_of_point()` / `material_of_point()` APIs and as a compatibility fallback. Preserve the existing public `material_of_grid()` return type, C-order (`z` fastest), `[start, stop)` bounds, and object identities through a compatibility adapter; FDTD and TFSF should consume the internal ID map directly.

Define an inherited, explicit bulk-lowering protocol for custom geometry. Parameter-only subclasses that preserve a built-in predicate should be able to opt into the vectorized path. Existing custom classes that only implement pointwise `in_object()` must remain correct through a bounded fallback and must fail neither silently nor by being misclassified as a built-in shape.

## Compatibility requirements

Preserve, or explicitly document an approved migration for:

- public import paths and class names under `gmes` and `gmes.pygeom`;
- constructor signatures, validation, attributes, inheritance, and `isinstance()` behavior for all geometry primitives;
- `Material` / `Compound` inheritance used by built-in and custom materials;
- `GeomBox`, `GeomBoxNode`, and `GeomBoxTree` point-query behavior;
- direct compatibility uses such as `GeomBoxTree.root.geom_list`;
- the first geometry as the no-match fallback, last-overlap-wins ordering, and immediate underlying-medium resolution;
- exact boundary inclusion rules for every primitive;
- rotated cones/cylinders, skew blocks/ellipsoids, shifted shells, infinite default-medium bounds, and collapsed dimensions;
- MPI-local Yee-coordinate mapping;
- FDTD and TFSF material mapping;
- deepcopy and pickle round trips, including fixtures created by the Cython implementation before and after initialization.
- the existing `Material` type requirement on `GeometricObject.material`;
- existing custom subclass overrides of `in_object()` and `geom_box()`.

Replacing extension types with Python classes may add implementation details such as `__dict__`; that is acceptable only if existing documented behavior and serialized state remain compatible.

Do not fold unrelated behavior changes into the port. In particular, the current `Shell.init()` appends to `box_list` when called repeatedly, and the inherited Cython `__reduce__` does not preserve arbitrary extra attributes on Python subclasses. Preserve the core built-in state and legacy payloads here; fix or deliberately improve those observable edge cases only through explicit tests and a separately reviewed compatibility decision.

## Performance verification

Add a dedicated geometry-mapping benchmark in addition to the initialization measurement from #99. Run the Cython reference and candidate in separate checkouts/processes on the same otherwise-idle machine, with identical Python, NumPy, compiler, workload, and thread settings. Record hardware, software, reference commit, raw samples, median, and peak RSS.

The performance non-regression guarantee applies to monotonic Cartesian Yee axes, every built-in geometry, FDTD bulk material mapping, and built-in TFSF mapping. Public scalar lookups and arbitrary custom pointwise geometry retain correctness and are timed separately, but cannot realistically be required to match compiled Cython microperformance. Custom geometry can opt into the bulk gate through the explicit vectorized protocol.

Cover at least:

- default-only 2-D and 3-D grids;
- the existing heterogeneous 16-cylinder case;
- many small objects and heavily overlapping objects;
- large `Sphere`, rotated `Cone` / `Cylinder`, skew `Block` / `Ellipsoid`;
- boundary and shifted `Shell`, including `Compound` overlap;
- 1-D, 2-D, 3-D, singleton/collapsed axes, real, and complex simulations;
- a representative pointwise custom-geometry fallback as a non-gating compatibility measurement;
- TFSF mapping and MPI-local coordinate partitions.

Performance gates:

- no statistically meaningful geometry-mapping, simulation-construction, or `FDTD.init()` regression across the representative built-in workload set;
- no individual representative built-in case more than 5% slower in median after enough repetitions to control noise, and no regression in the geometric mean;
- no more than 2% steady-state timestep regression (none is expected because this change must not alter timestep kernels);
- keep peak RSS at or below `1.05 * baseline + 16 MiB`, use a working set bounded by tile size, and investigate any larger increase before merge;
- report custom-fallback and scalar-query performance separately and document any tradeoff without weakening functional compatibility.

## Correctness verification

- Compare complete material-ID and underlying-ID maps with the Cython reference, not only counts or final checksums.
- Exercise exact boundary points and `numpy.nextafter()` on both sides so a vectorized operation-order change cannot silently reclassify cells.
- Compare updater membership, ordering, coefficients, and persistent initial state produced for all supported material families and six Yee components.
- Reuse seeded nonzero fields and compare complete fields after selected timesteps.
- Run focused geometry, material, source, FDTD, pickle/deepcopy, MPI, build, wheel, and source-distribution tests.
- Exercise Linux x86-64 and macOS arm64 packaging and runtime smoke tests.

## Implementation work

- [ ] Record Cython-reference correctness artifacts and benchmark results at `f3f0627`.
- [ ] Expand primitive, overlap, `Compound`, custom subclass, pickle, and deepcopy regression coverage.
- [ ] Define the backend-neutral geometry-map and custom bulk-lowering protocols.
- [ ] Implement bounded NumPy vectorization for every built-in primitive.
- [ ] Route FDTD and TFSF initialization through the new map while preserving the current C++ updater path.
- [ ] Preserve point-query, public `material_of_grid()`, tree-facade, and custom-geometry fallback behavior.
- [ ] Add isolated geometry mapping, construction, initialization, memory, and fallback benchmarks and satisfy the non-regression gates.
- [ ] Replace `src/pygeom.pyx` with the compatible Python module.
- [ ] Remove the `gmes.pygeom` extension declaration, `cythonize()` use, Cython build constraints, cache keys, extension allow-list entries, and obsolete release checks.
- [ ] Update the lockfile, sdist/wheel contents, README, changelog, CI, and packaging smoke tests.
- [ ] Verify that no generated Cython artifacts enter source or wheel distributions.

## Relationships

- Follow-up to #100, applying the Python-layer simplification to the remaining `gmes.pygeom` Cython extension.
- Builds on #102 and PR #111. Preserve their bounded batch-mapping semantics, correctness coverage, and initialization-performance gains rather than reverting to pointwise Python iteration.
- Use the benchmark introduced by #99, with `f3f0627` as the initial reference commit, for initialization, timestep, and memory non-regression gates.
- Prepare the backend-neutral geometry lowering needed by a future re-scope of #75; this issue does not implement PyTorch or change timestep kernels.
- Supersede only the Rust geometry-compiler assumption in #104. This issue does not close or otherwise complete the broader native-solver migration in #104.

## Completion criteria

This issue is complete when `gmes.pygeom` is an import-compatible Python module, no Cython source or build dependency remains, complete mapping and simulation parity is demonstrated against the recorded reference, the stated performance and memory gates pass, and Linux/macOS distributions build and run without Cython.
